words = ("apple", "banana", "orange", "mango", "grape",
    "lemon", "lime", "peach", "pear", "plum",
    "cherry", "melon", "kiwi", "papaya", "guava",
    "coconut", "apricot", "fig", "date", "lychee",
    "pineapple", "watermelon", "strawberry", "blueberry",
    "raspberry", "blackberry", "cranberry", "pomegranate",
    "avocado", "passionfruit","dragonfruit", "jackfruit", "starfruit", "durian",
    "rambutan", "longan", "mangosteen", "sapodilla",
    "custardapple", "soursop", "breadfruit", "pomelo",
    "tamarind", "persimmon", "loquat", "feijoa",
    "jabuticaba", "ackee", "salak", "langsat" ,"strawberry", "blueberry", "blackberry",
    "raspberry", "cranberry", "gooseberry",
    "mulberry", "boysenberry", "elderberry",
    "huckleberry", "currant",  "cherimoya", "miraclefruit", "cloudberry",
    "physalis", "quince", "medlar", "yuzu",
    "uglifruit", "bilberry", "rowanberry",
    "marionberry", "dewberry", "serviceberry",
    "nance", "canistel", "lucuma")